/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.SwingWorker;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.JTextComponent;
import negocio.PersonaServicio;

/**
 *
 * @author sebas
 */
public class busquedaFrame extends javax.swing.JFrame {

    private DefaultTableModel facturaModel;
    private int siguienteId = 1;
    private int currentRowIndex = -1;
    private PersonaServicio personaServicio = new PersonaServicio();

    /**
     * Creates new form busquedaFrame
     */
    public busquedaFrame() {

        initComponents();

        String[] columnas = {"ID", "Persona", "Productos"};
        facturaModel = new DefaultTableModel(columnas, 0);
        tblFactura.setModel(facturaModel);

        jComboBoxPersona.setEditable(true);
        jComboBoxProducto.setEditable(true);
        JTextComponent editorPersona
                = (JTextComponent) jComboBoxPersona.getEditor().getEditorComponent();
        JTextComponent editorProducto
                = (JTextComponent) jComboBoxProducto.getEditor().getEditorComponent();

        // 3. Añadir DocumentListener para disparar búsquedas
//        DocumentListener dl = new DocumentListener() {
//            public void insertUpdate(DocumentEvent e) {
//                fetchPersonaSuggestions();
//            }
//
//            public void removeUpdate(DocumentEvent e) {
//                fetchPersonaSuggestions();
//            }
//
//            public void changedUpdate(DocumentEvent e) {
//                /* no hace falta */ }
//        };
//        editorPersona.getDocument().addDocumentListener(dl);
//
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxProducto = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFactura = new javax.swing.JTable();
        butAgregarPersona = new javax.swing.JButton();
        butAgregarProducto = new javax.swing.JButton();
        jComboBoxPersona = new javax.swing.JComboBox<>();
        butCambiarPersona = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Buscar Usuario");

        jLabel3.setText("Nombre del usuario:");

        jLabel2.setText("Buscar Producto");

        jLabel4.setText("Nombre del producto:");

        jComboBoxProducto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addContainerGap(101, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jComboBoxProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        tblFactura.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblFactura);

        butAgregarPersona.setText("Seleccionar");
        butAgregarPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butAgregarPersonaActionPerformed(evt);
            }
        });

        butAgregarProducto.setText("Agregar");
        butAgregarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butAgregarProductoActionPerformed(evt);
            }
        });

        butCambiarPersona.setText("Cambiar");
        butCambiarPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butCambiarPersonaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(butCambiarPersona)
                                .addGap(18, 18, 18)
                                .addComponent(butAgregarPersona)
                                .addGap(409, 409, 409)
                                .addComponent(butAgregarProducto))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 745, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 94, Short.MAX_VALUE))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(95, 95, 95)
                    .addComponent(jComboBoxPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(575, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butAgregarProducto)
                    .addComponent(butAgregarPersona)
                    .addComponent(butCambiarPersona))
                .addGap(79, 79, 79)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(78, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(106, 106, 106)
                    .addComponent(jComboBoxPersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(549, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butAgregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butAgregarProductoActionPerformed

        if (currentRowIndex >= 0) {
            // 1. Leer producto seleccionado
            String producto = (String) jComboBoxProducto.getSelectedItem();  // :contentReference[oaicite:9]{index=9}

            // 2. Concatenar al contenido existente
            String existentes = (String) facturaModel.getValueAt(currentRowIndex, 2);
            String actualizados = existentes.isEmpty()
                    ? producto
                    : existentes + ", " + producto;

            // 3. Actualizar la celda de productos
            facturaModel.setValueAt(actualizados, currentRowIndex, 2);    // :contentReference[oaicite:10]{index=10}

        } else {
            // Advertencia si no se ha agregado aún ninguna persona
            JOptionPane.showMessageDialog(
                    this,
                    "Primero selecciona una persona",
                    "Validación",
                    JOptionPane.WARNING_MESSAGE
            );  // :contentReference[oaicite:11]{index=11}
        }

    }//GEN-LAST:event_butAgregarProductoActionPerformed

    private void butAgregarPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butAgregarPersonaActionPerformed

        String persona = (String) jComboBoxPersona.getSelectedItem();  // :contentReference[oaicite:5]{index=5}

        // 2. Añadir fila: ID, Persona, Productos vacío
        facturaModel.addRow(new Object[]{siguienteId++, persona, ""});  // :contentReference[oaicite:6]{index=6}
        currentRowIndex = facturaModel.getRowCount() - 1;

        // 3. Deshabilitar selección de persona
        jComboBoxPersona.setEnabled(false);
        butAgregarPersona.setEnabled(false);

    }//GEN-LAST:event_butAgregarPersonaActionPerformed

    private void butCambiarPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butCambiarPersonaActionPerformed

        // Rehabilitar selección de persona
        jComboBoxPersona.setEnabled(true);
        butAgregarPersona.setEnabled(true);  // :contentReference[oaicite:8]{index=8}

        // Resetear índice de fila actual
        currentRowIndex = -1;
        jComboBoxPersona.setSelectedItem(null);

    }//GEN-LAST:event_butCambiarPersonaActionPerformed

//    private void fetchPersonaSuggestions() {
//        JTextComponent editor = (JTextComponent) jComboBoxPersona.getEditor().getEditorComponent();
//        String texto = editor.getText(); // Guardamos el texto escrito
//
//        if (texto.length() < 2) {
//            return; // No buscar con menos de 2 caracteres
//        }
//        new SwingWorker<List<String>, Void>() {
//            protected List<String> doInBackground() {
////                return personaServicio.buscarPorNombreParcial(texto); // Aquí obtienes los resultados
//            }
//
//            protected void done() {
//                try {
//                    List<String> resultados = get();
//
//                    // Creamos un nuevo modelo con los resultados
//                    DefaultComboBoxModel<String> modelo = new DefaultComboBoxModel<>();
//                    for (String resultado : resultados) {
//                        modelo.addElement(resultado); // Agrega "Nombre Apellido"
//                    }
//
//                    // Desvinculamos momentáneamente el listener de eventos para evitar bucles
//                    jComboBoxPersona.setEditable(false);
//                    jComboBoxPersona.setModel(modelo); // Actualizamos el modelo
//
//                    // Restauramos el texto del usuario manualmente
//                    jComboBoxPersona.setEditable(true);
//                    editor.setText(texto);
//
//                    // Mostramos el menú desplegable
//                    jComboBoxPersona.showPopup();
//
//                } catch (Exception ex) {
//                    ex.printStackTrace();
//                }
//            }
//        }.execute();
//    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(busquedaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(busquedaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(busquedaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(busquedaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new busquedaFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butAgregarPersona;
    private javax.swing.JButton butAgregarProducto;
    private javax.swing.JButton butCambiarPersona;
    private javax.swing.JComboBox<String> jComboBoxPersona;
    private javax.swing.JComboBox<String> jComboBoxProducto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblFactura;
    // End of variables declaration//GEN-END:variables
}
