/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

import java.awt.Color;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import javax.swing.table.DefaultTableModel;
import modelo.Categoria;
import modelo.Producto;
import negocio.ProductoServicio;

/**
 *
 * @author sebas
 */
public class SistemaProducto extends javax.swing.JFrame {

    private ProductoServicio servicio;
    private final DefaultTableModel modelo;
    private List<Producto> listadoProductos;

    private final Border bordeRojo = BorderFactory.createLineBorder(Color.RED, 2);
    private final Border bordeNegro = BorderFactory.createLineBorder(Color.BLACK, 1);

    public SistemaProducto() {
        initComponents();
        for (Categoria cat : Categoria.values()) {
            String nombreCategoria = cat.name().charAt(0) + cat.name().substring(1).toLowerCase();
            this.comboBoxCategoria.addItem(nombreCategoria);
        }
        this.servicio = new ProductoServicio();

        this.modelo = new DefaultTableModel(
                new String[]{"Nombre", "Código", "Categoría", "Precio", "Stock", "IVA"}, 0
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        this.tbListProduct.setModel(modelo);

        ActualizarTablaRegistro();
        LimpiarFormulario();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSystemProduct = new javax.swing.JLabel();
        lblCodeProduct = new javax.swing.JLabel();
        txtCodeProduct = new javax.swing.JTextField();
        lblNameProduct = new javax.swing.JLabel();
        txtNameProduct = new javax.swing.JTextField();
        lblPriceProduct = new javax.swing.JLabel();
        txtPriceProduct = new javax.swing.JTextField();
        btnRegisterProduct = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbListProduct = new javax.swing.JTable();
        btnUpdateProduct = new javax.swing.JButton();
        btnDeleteProduct = new javax.swing.JButton();
        lblListProdutcRegister = new javax.swing.JLabel();
        btnClearProduct = new javax.swing.JButton();
        lblIVAProduct = new javax.swing.JLabel();
        txtStockProduct = new javax.swing.JTextField();
        lblStockProduct1 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        comboBoxCategoria = new javax.swing.JComboBox<>();
        lblcategoriaProduct = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(0, 0));

        lblSystemProduct.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblSystemProduct.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSystemProduct.setText("SISTEMA PRODUCTO");

        lblCodeProduct.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCodeProduct.setText("Codigo producto");

        txtCodeProduct.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtCodeProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodeProductActionPerformed(evt);
            }
        });

        lblNameProduct.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblNameProduct.setText("Nombre producto");

        txtNameProduct.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtNameProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameProductActionPerformed(evt);
            }
        });

        lblPriceProduct.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPriceProduct.setText("Precio");

        txtPriceProduct.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnRegisterProduct.setBackground(new java.awt.Color(102, 255, 102));
        btnRegisterProduct.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRegisterProduct.setForeground(new java.awt.Color(0, 0, 0));
        btnRegisterProduct.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnRegisterProduct.setLabel("Registrar");
        btnRegisterProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterProductActionPerformed(evt);
            }
        });

        tbListProduct.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tbListProduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nombre", "Codigo", "Precio"
            }
        ));
        tbListProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbListProductMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbListProduct);

        btnUpdateProduct.setBackground(new java.awt.Color(255, 255, 102));
        btnUpdateProduct.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnUpdateProduct.setForeground(new java.awt.Color(0, 0, 0));
        btnUpdateProduct.setText("Actualizar");
        btnUpdateProduct.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnUpdateProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateProductActionPerformed(evt);
            }
        });

        btnDeleteProduct.setBackground(new java.awt.Color(255, 51, 51));
        btnDeleteProduct.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDeleteProduct.setForeground(new java.awt.Color(0, 0, 0));
        btnDeleteProduct.setText("Eliminar");
        btnDeleteProduct.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnDeleteProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteProductActionPerformed(evt);
            }
        });

        lblListProdutcRegister.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblListProdutcRegister.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblListProdutcRegister.setText("LISTA DE PRODUCTOS REGISTRADOS");

        btnClearProduct.setBackground(new java.awt.Color(204, 204, 204));
        btnClearProduct.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnClearProduct.setForeground(new java.awt.Color(0, 0, 0));
        btnClearProduct.setText("Limpiar");
        btnClearProduct.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnClearProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearProductActionPerformed(evt);
            }
        });

        lblIVAProduct.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblIVAProduct.setText("IVA");

        txtStockProduct.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtStockProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStockProductActionPerformed(evt);
            }
        });

        lblStockProduct1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblStockProduct1.setText("Stock");

        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        lblcategoriaProduct.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblcategoriaProduct.setText("Categoría");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSystemProduct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNameProduct)
                                    .addComponent(lblCodeProduct)
                                    .addComponent(lblPriceProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(41, 41, 41)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNameProduct, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                                    .addComponent(txtCodeProduct)
                                    .addComponent(txtPriceProduct)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnRegisterProduct, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                    .addComponent(btnDeleteProduct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnUpdateProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(40, 40, 40)
                                        .addComponent(btnClearProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblStockProduct1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblcategoriaProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblIVAProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(63, 63, 63)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtStockProduct)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jCheckBox1)
                                            .addComponent(comboBoxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addGap(0, 66, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(lblListProdutcRegister, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(72, 72, 72))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSystemProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblListProdutcRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNameProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNameProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCodeProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCodeProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPriceProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPriceProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtStockProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblStockProduct1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(comboBoxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(lblcategoriaProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblIVAProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBox1))
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnRegisterProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnUpdateProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDeleteProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClearProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameProductActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameProductActionPerformed

    private void txtCodeProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodeProductActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodeProductActionPerformed

    private void btnRegisterProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterProductActionPerformed

        String nombre = txtNameProduct.getText().trim();
        String codigo = txtCodeProduct.getText().trim();
        String precioTexto = txtPriceProduct.getText().trim();
        String stockTexto = txtStockProduct.getText().trim();

        if (!nombre.matches("[a-zA-ZáéíóúÁÉÍÓÚñÑ ]+")) {
            JOptionPane.showMessageDialog(this, "El nombre solo debe contener letras.");
            txtNameProduct.setBorder(bordeRojo);
            return;
        } else {
            txtNameProduct.setBorder(bordeNegro);
        }

        if (!codigo.matches("\\d+")) {
            JOptionPane.showMessageDialog(this, "El código solo debe contener números.");
            txtCodeProduct.setBorder(bordeRojo);
            return;
        } else {
            txtCodeProduct.setBorder(bordeNegro);
        }

        double precio;
        try {
            precio = Double.parseDouble(precioTexto);
            if (precio <= 0) {
                throw new NumberFormatException();
            }
            txtPriceProduct.setBorder(bordeNegro);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El precio debe ser un número positivo.");
            txtPriceProduct.setBorder(bordeRojo);
            return;
        }

        int stock;
        try {
            stock = Integer.parseInt(stockTexto);
            if (stock < 0) {
                throw new NumberFormatException();
            }
            txtStockProduct.setBorder(bordeNegro);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El stock debe ser un número entero no negativo.");
            txtStockProduct.setBorder(bordeRojo);
            return;
        }

        RegistrarNuevoProducto();


    }//GEN-LAST:event_btnRegisterProductActionPerformed

    private void tbListProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbListProductMouseClicked
        LlenarFormularioDesdeTabla();
    }//GEN-LAST:event_tbListProductMouseClicked

    private void btnUpdateProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateProductActionPerformed
        ActualizarDatosProducto();
    }//GEN-LAST:event_btnUpdateProductActionPerformed

    private void btnDeleteProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteProductActionPerformed
        EliminarRegistroProducto();
    }//GEN-LAST:event_btnDeleteProductActionPerformed

    private void btnClearProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearProductActionPerformed
        LimpiarFormulario();
    }//GEN-LAST:event_btnClearProductActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void txtStockProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStockProductActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStockProductActionPerformed

    private void RegistrarNuevoProducto() {
        if (ValidarFormulario()) {
            Producto nuevoProducto = GenerarDatosProducto();
            if (nuevoProducto == null) {
                return;
            }

            int registro = servicio.AgregarNuevoProducto(nuevoProducto);
            switch (registro) {
                case 0:
                    MostrarMensajePanel("Ya existe el producto con ese número de código.",
                            "Advertencia", JOptionPane.WARNING_MESSAGE);
                    break;

                case 1:
                    MostrarMensajePanel("Registro exitoso.",
                            "Información", JOptionPane.INFORMATION_MESSAGE);
                    ActualizarTablaRegistro();
                    LimpiarFormulario();
                    break;

                case 2:
                    MostrarMensajePanel("Error interno, intentelo más tarde.",
                            "Error", JOptionPane.ERROR_MESSAGE);
                    break;
            }
        } else {
            MostrarMensajePanel("Debe completar todos los campos obligatorios.",
                    "Advertencia", JOptionPane.INFORMATION_MESSAGE);
        }
    }

    private void ActualizarDatosProducto() {
        int filaSeleccionada = this.tbListProduct.getSelectedRow();
        if (filaSeleccionada >= 0) {
            if (ValidarFormulario()) {
                Producto actualizarProducto = GenerarDatosProducto();
                if (actualizarProducto == null) {
                    return;
                }
                int idProducto = this.listadoProductos.get(filaSeleccionada).getId();
                boolean actualizado = this.servicio.ActualizarProducto(idProducto, actualizarProducto);

                if (actualizado) {
                    MostrarMensajePanel("Registro actualizado.",
                            "Información", JOptionPane.INFORMATION_MESSAGE);
                    ActualizarTablaRegistro();
                    LimpiarFormulario();
                } else {
                    MostrarMensajePanel("No se pudo actualizar el registro.",
                            "Advertencia", JOptionPane.WARNING_MESSAGE);
                }
            }
        }
    }

    private void EliminarRegistroProducto() {
        int filaSeleccionada = this.tbListProduct.getSelectedRow();

        if (filaSeleccionada >= 0) {
            int confirmacion = JOptionPane.showConfirmDialog(null,
                    "¿Estás seguro de eliminar este producto?",
                    "Confirmar eliminación",
                    JOptionPane.YES_NO_OPTION);

            if (confirmacion == JOptionPane.YES_OPTION) {
                int idProducto = this.listadoProductos.get(filaSeleccionada).getId();
                boolean eliminado = this.servicio.EliminarProductoPorId(idProducto);
                if (eliminado) {
                    MostrarMensajePanel("Producto eliminado correctamente.",
                            "", JOptionPane.INFORMATION_MESSAGE);
                    ActualizarTablaRegistro();
                    LimpiarFormulario();
                } else {
                    MostrarMensajePanel("No se pudo eliminar el producto.",
                            "", JOptionPane.INFORMATION_MESSAGE);
                }
            }
        }
    }

    private Producto GenerarDatosProducto() {
        try {
            String nombre = this.txtNameProduct.getText().trim();
            String codigo = this.txtCodeProduct.getText().trim();
            double precio = Double.parseDouble(this.txtPriceProduct.getText().trim());
            int stock = Integer.parseInt(this.txtStockProduct.getText().trim());
            boolean iva = this.jCheckBox1.isSelected();

            if (nombre.isEmpty() || codigo.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Nombre y código son obligatorios", "Error", JOptionPane.ERROR_MESSAGE);
                return null;
            }

            if (precio <= 0 || stock < 0) {
                JOptionPane.showMessageDialog(this, "Precio y stock deben ser valores positivos", "Error", JOptionPane.ERROR_MESSAGE);
                return null;
            }

            Categoria categoria;
            try {
                String categoriaStr = ((String) this.comboBoxCategoria.getSelectedItem()).toUpperCase();
                categoria = Categoria.valueOf(categoriaStr);
            } catch (IllegalArgumentException e) {
                JOptionPane.showMessageDialog(this, "Categoría inválida seleccionada", "Error", JOptionPane.ERROR_MESSAGE);
                return null;
            } catch (NullPointerException e) {
                JOptionPane.showMessageDialog(this, "No se ha seleccionado categoría", "Error", JOptionPane.ERROR_MESSAGE);
                return null;
            }

            return new Producto(codigo, nombre, categoria, precio, stock, iva);

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Formato inválido en precio o stock", "Error", JOptionPane.ERROR_MESSAGE);
            return null;
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error inesperado: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            return null;
        }
    }

    private void MostrarMensajePanel(String msm, String cabezera, int tipoPanel) {
        JOptionPane.showMessageDialog(null, msm, cabezera, tipoPanel);
    }

    private boolean ValidarFormulario() {
        this.txtNameProduct.setBorder(this.txtNameProduct.getText().isEmpty() ? this.bordeRojo : this.bordeNegro);
        this.txtCodeProduct.setBorder(this.txtCodeProduct.getText().isEmpty() ? this.bordeRojo : this.bordeNegro);
        this.txtPriceProduct.setBorder(this.txtPriceProduct.getText().isEmpty() ? this.bordeRojo : this.bordeNegro);
        this.txtStockProduct.setBorder(this.txtStockProduct.getText().isEmpty() ? this.bordeRojo : this.bordeNegro);

        return !(this.txtNameProduct.getText().isEmpty() || this.txtCodeProduct.getText().isEmpty()
                || this.txtPriceProduct.getText().isEmpty() || this.txtStockProduct.getText().isEmpty());
    }

    private void ActualizarTablaRegistro() {
        this.modelo.setRowCount(0);

        this.listadoProductos = this.servicio.ListarProductos();
        for (Producto productoActual : this.listadoProductos) {
            Object[] fila = new Object[]{
                productoActual.getNombre(),
                productoActual.getCodigo(),
                productoActual.getCategoria().toString(),
                productoActual.getPrecio(),
                productoActual.getStock(),
                productoActual.isIva() ? "Sí" : "No"
            };
            this.modelo.addRow(fila);
        }

    }

    private void LlenarFormularioDesdeTabla() {
        int filaSeleccionada = this.tbListProduct.getSelectedRow();

        if (filaSeleccionada >= 0) {
            this.btnDeleteProduct.setEnabled(true);
            this.btnUpdateProduct.setEnabled(true);
            this.btnRegisterProduct.setEnabled(false);

            String nombre = this.tbListProduct.getValueAt(filaSeleccionada, 0).toString();
            String codigo = this.tbListProduct.getValueAt(filaSeleccionada, 1).toString();
            String precio = this.tbListProduct.getValueAt(filaSeleccionada, 2).toString();
            String stock = this.tbListProduct.getValueAt(filaSeleccionada, 3).toString();
            String iva = this.tbListProduct.getValueAt(filaSeleccionada, 4).toString();

            this.txtNameProduct.setText(nombre);
            this.txtCodeProduct.setText(codigo);
            this.txtPriceProduct.setText(precio);
            this.txtStockProduct.setText(stock);
            this.jCheckBox1.setSelected("Sí".equals(iva));
        }
    }

    private void LimpiarFormulario() {
        this.txtNameProduct.setText("");
        this.txtCodeProduct.setText("");
        this.txtPriceProduct.setText("");
        this.txtStockProduct.setText("");
        this.jCheckBox1.setSelected(false);

        this.tbListProduct.clearSelection();
        this.btnRegisterProduct.setEnabled(true);
        this.btnDeleteProduct.setEnabled(false);
        this.btnUpdateProduct.setEnabled(false);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SistemaProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SistemaProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SistemaProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SistemaProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SistemaProducto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClearProduct;
    private javax.swing.JButton btnDeleteProduct;
    private javax.swing.JButton btnRegisterProduct;
    private javax.swing.JButton btnUpdateProduct;
    private javax.swing.JComboBox<String> comboBoxCategoria;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCodeProduct;
    private javax.swing.JLabel lblIVAProduct;
    private javax.swing.JLabel lblListProdutcRegister;
    private javax.swing.JLabel lblNameProduct;
    private javax.swing.JLabel lblPriceProduct;
    private javax.swing.JLabel lblStockProduct1;
    private javax.swing.JLabel lblSystemProduct;
    private javax.swing.JLabel lblcategoriaProduct;
    private javax.swing.JTable tbListProduct;
    private javax.swing.JTextField txtCodeProduct;
    private javax.swing.JTextField txtNameProduct;
    private javax.swing.JTextField txtPriceProduct;
    private javax.swing.JTextField txtStockProduct;
    // End of variables declaration//GEN-END:variables
}
