/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Cliente;
import modelo.DetalleFactura;
import modelo.Factura;
import modelo.Persona;
import modelo.Producto;
import negocio.FacturaServicio;
import negocio.clienteServicio;

/**
 *
 * @author sebas
 */
public class SistemaFactura extends javax.swing.JFrame {

    private List<DetalleFactura> detallesFactura = new ArrayList();
    private final FacturaServicio servicio;
    private Persona personaEncontrada;
    private Producto productoEncontrado;
    private final DefaultTableModel modelo;

    /**
     * Creates new form SistemaFactura
     */
    public SistemaFactura() {
        initComponents();
        txtAmountProduct.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                char c = evt.getKeyChar();
                if (!Character.isDigit(c) && c != '\b') {
                    evt.consume();
                    JOptionPane.showMessageDialog(null, "Solo se permiten números en el campo cantidad");
                }
            }
        });

        this.servicio = new FacturaServicio();

        this.modelo = new DefaultTableModel(
                new String[]{"Cantidad", "Descripción", "Precio Unitario", "Total"}, 0
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        this.tblListDetails.setModel(modelo);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtNumIdenUser = new javax.swing.JTextField();
        btnSearchProduct = new javax.swing.JButton();
        lblCodeProduct = new javax.swing.JLabel();
        txtCodeProduct = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblListDetails = new javax.swing.JTable();
        txtAmountProduct = new javax.swing.JTextField();
        lblAmountProduct = new javax.swing.JLabel();
        lblPriceProduct = new javax.swing.JLabel();
        txtPriceProduct = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        btnGenerateInvoice = new javax.swing.JButton();
        lblSystem = new javax.swing.JLabel();
        lblHeaderName1 = new javax.swing.JLabel();
        lblInfoProduct = new javax.swing.JLabel();
        lblNumIdUser = new javax.swing.JLabel();
        txtNumIdUser = new javax.swing.JTextField();
        lblEmailUser = new javax.swing.JLabel();
        txtEmailUser = new javax.swing.JTextField();
        lblLastnameUser = new javax.swing.JLabel();
        txtLastnameUser = new javax.swing.JTextField();
        lblNameUser = new javax.swing.JLabel();
        txtNameUser = new javax.swing.JTextField();
        lblHeaderName3 = new javax.swing.JLabel();
        btnDeleteProductBill = new javax.swing.JButton();
        lblSubtotal = new javax.swing.JLabel();
        lblIva = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        lblTotalPrice = new javax.swing.JLabel();
        lblIvaPrice = new javax.swing.JLabel();
        lblSubtotalPrice = new javax.swing.JLabel();
        txtNameProduct = new javax.swing.JTextField();
        lblNameProduct = new javax.swing.JLabel();
        lblIva1 = new javax.swing.JLabel();
        chkAplicarDescuento = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jButton1.setBackground(new java.awt.Color(33, 255, 107));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Buscar Cliente");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Cédula");

        txtNumIdenUser.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnSearchProduct.setBackground(new java.awt.Color(38, 255, 110));
        btnSearchProduct.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSearchProduct.setForeground(new java.awt.Color(0, 0, 0));
        btnSearchProduct.setText("Buscar Producto");
        btnSearchProduct.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnSearchProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchProductActionPerformed(evt);
            }
        });

        lblCodeProduct.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCodeProduct.setText("Buscar producto por Código");

        tblListDetails.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tblListDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Cantidad", "Descripción", "Precio Unitario", "Total"
            }
        ));
        jScrollPane1.setViewportView(tblListDetails);

        txtAmountProduct.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblAmountProduct.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblAmountProduct.setText("Cantidad");

        lblPriceProduct.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPriceProduct.setText("Precio");

        txtPriceProduct.setEditable(false);
        txtPriceProduct.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtPriceProduct.setEnabled(false);

        jButton3.setBackground(new java.awt.Color(33, 255, 107));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 0, 0));
        jButton3.setText("Agregar Producto");
        jButton3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        btnGenerateInvoice.setBackground(new java.awt.Color(196, 157, 19));
        btnGenerateInvoice.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnGenerateInvoice.setForeground(new java.awt.Color(0, 0, 0));
        btnGenerateInvoice.setText("Generar Factura");
        btnGenerateInvoice.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnGenerateInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateInvoiceActionPerformed(evt);
            }
        });

        lblSystem.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblSystem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSystem.setText("FACTURACIÓN");

        lblHeaderName1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblHeaderName1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeaderName1.setText("DETALLES FACTURA");

        lblInfoProduct.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblInfoProduct.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblInfoProduct.setText("Información del producto:");

        lblNumIdUser.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblNumIdUser.setText("Número de cédula");

        txtNumIdUser.setEditable(false);
        txtNumIdUser.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtNumIdUser.setEnabled(false);

        lblEmailUser.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblEmailUser.setText("Correo electrónico");

        txtEmailUser.setEditable(false);
        txtEmailUser.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtEmailUser.setEnabled(false);

        lblLastnameUser.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblLastnameUser.setText("Apellido");

        txtLastnameUser.setEditable(false);
        txtLastnameUser.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtLastnameUser.setEnabled(false);

        lblNameUser.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblNameUser.setText("Nombre");

        txtNameUser.setEditable(false);
        txtNameUser.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtNameUser.setEnabled(false);

        lblHeaderName3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblHeaderName3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblHeaderName3.setText("Información del Cliente:");

        btnDeleteProductBill.setBackground(new java.awt.Color(255, 86, 86));
        btnDeleteProductBill.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDeleteProductBill.setForeground(new java.awt.Color(0, 0, 0));
        btnDeleteProductBill.setText("Eliminar Detalle");
        btnDeleteProductBill.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnDeleteProductBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteProductBillActionPerformed(evt);
            }
        });

        lblSubtotal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblSubtotal.setText("SUBTOTAL:");

        lblIva.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblIva.setText("IVA 15%:");

        lblTotal.setFont(new java.awt.Font("Source Han Sans CN Bold", 1, 24)); // NOI18N
        lblTotal.setText("TOTAL:");

        lblTotalPrice.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTotalPrice.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTotalPrice.setText("00");

        lblIvaPrice.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblIvaPrice.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblIvaPrice.setText("00");

        lblSubtotalPrice.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblSubtotalPrice.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSubtotalPrice.setText("00");

        txtNameProduct.setEditable(false);
        txtNameProduct.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtNameProduct.setEnabled(false);

        lblNameProduct.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblNameProduct.setText("Nombre");

        lblIva1.setFont(new java.awt.Font("Source Han Sans CN Bold", 1, 12)); // NOI18N
        lblIva1.setText("Aplicar descuento:");

        chkAplicarDescuento.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                chkAplicarDescuentoStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSystem, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(106, 106, 106)
                .addComponent(lblHeaderName1, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNameProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblNameProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblPriceProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPriceProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtCodeProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnSearchProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(148, 148, 148))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblAmountProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAmountProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDeleteProductBill, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(233, 233, 233)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(btnGenerateInvoice, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblSubtotal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblIva, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTotal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblIva1, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblTotalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblIvaPrice, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblSubtotalPrice, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(chkAplicarDescuento))))
                .addGap(49, 49, 49))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txtNameUser, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(lblNameUser, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lblLastnameUser, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtLastnameUser, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addComponent(lblInfoProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblHeaderName3, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblCodeProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblEmailUser, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtNumIdUser, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(7, 7, 7))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblNumIdUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txtNumIdenUser, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtEmailUser, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(0, 0, Short.MAX_VALUE)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(66, 66, 66))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(0, 0, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(686, 686, 686)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHeaderName1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSystem, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNumIdenUser, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblHeaderName3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNameUser, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblLastnameUser, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNameUser, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLastnameUser, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblNumIdUser, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNumIdUser, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblEmailUser, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtEmailUser, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblInfoProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCodeProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCodeProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSearchProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblNameProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblPriceProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtNameProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPriceProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblAmountProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtAmountProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDeleteProductBill, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)))
                        .addGap(46, 46, 46))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblSubtotal)
                                .addGap(37, 37, 37)
                                .addComponent(lblIva1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblSubtotalPrice)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblIvaPrice)
                                    .addComponent(lblIva))
                                .addGap(18, 18, 18)
                                .addComponent(chkAplicarDescuento)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblTotalPrice)
                                    .addComponent(lblTotal))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGenerateInvoice, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        BuscarPersona();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnSearchProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchProductActionPerformed
        BuscarProducto();
    }//GEN-LAST:event_btnSearchProductActionPerformed

    private void btnGenerateInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateInvoiceActionPerformed
        RegistrarFactura();
    }//GEN-LAST:event_btnGenerateInvoiceActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        AgregarDetalleFactura();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnDeleteProductBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteProductBillActionPerformed
        EliminarDetalle();
    }//GEN-LAST:event_btnDeleteProductBillActionPerformed

    private void chkAplicarDescuentoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_chkAplicarDescuentoStateChanged
        ActualizarTablaRegistro();

    }//GEN-LAST:event_chkAplicarDescuentoStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SistemaFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SistemaFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SistemaFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SistemaFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SistemaFactura().setVisible(true);
            }
        });
    }

    private void BuscarPersona() {
        String cedula = this.txtNumIdenUser.getText();

        if (!cedula.matches("\\d+")) {
            JOptionPane.showMessageDialog(this, "La cédula debe contener solo números.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        this.personaEncontrada = this.servicio.BuscarPersonaPorCedula(cedula);

        if (this.personaEncontrada != null) {
            this.txtNameUser.setText(this.personaEncontrada.getNombre());
            this.txtLastnameUser.setText(this.personaEncontrada.getApellido());
            this.txtNumIdUser.setText(this.personaEncontrada.getNumIdentificacion());
            this.txtEmailUser.setText(this.personaEncontrada.getCorreo());
        } else {
            JOptionPane.showMessageDialog(this, "Persona no encontrada.", "Información", JOptionPane.INFORMATION_MESSAGE);
        }
    }

    private void BuscarProducto() {
        String codigo = this.txtCodeProduct.getText();

        if (!codigo.matches("\\d+")) {
            JOptionPane.showMessageDialog(this, "El código del producto debe contener solo números.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        this.productoEncontrado = this.servicio.BuscarProductoPorCodigo(codigo);

        if (this.productoEncontrado != null) {
            this.txtPriceProduct.setText(String.valueOf(this.productoEncontrado.getPrecio()));
            this.txtNameProduct.setText(this.productoEncontrado.getNombre());
        } else {
            JOptionPane.showMessageDialog(this, "Producto no encontrado.", "Información", JOptionPane.INFORMATION_MESSAGE);
        }
    }

    private void AgregarDetalleFactura() {
        try {
            int cantidad = Integer.parseInt(this.txtAmountProduct.getText());
            if (this.productoEncontrado != null) {
                if (cantidad <= this.productoEncontrado.getStock()) {
                    DetalleFactura nuevoDetalle = new DetalleFactura(
                            cantidad, (float) this.productoEncontrado.getPrecio(),
                            this.productoEncontrado
                    );
                    this.detallesFactura.add(nuevoDetalle);
                    ActualizarTablaRegistro();
                } else {
                    JOptionPane.showMessageDialog(this, "Stock insuficiente.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Cantidad inválida.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void EliminarDetalle() {
        int filaSeleccionada = this.tblListDetails.getSelectedRow();

        if (filaSeleccionada >= 0) {
            int confirmacion = JOptionPane.showConfirmDialog(null,
                    "¿Estás seguro de eliminar el detalle: "
                    + this.detallesFactura.get(filaSeleccionada).getProducto().getNombre(),
                    "Confirmar eliminación",
                    JOptionPane.YES_NO_OPTION);

            if (confirmacion == JOptionPane.YES_OPTION) {
                this.detallesFactura.remove(filaSeleccionada);
                ActualizarTablaRegistro();
            }
        }
    }

    private void ActualizarTablaRegistro() {
        float subTotal = 0;
        this.modelo.setRowCount(0);

        for (DetalleFactura detalleActual : this.detallesFactura) {
            float total = detalleActual.getCantidad() * detalleActual.getPrecioUnitario();
            subTotal += total;
            Object[] fila = new Object[]{
                detalleActual.getCantidad(),
                detalleActual.getProducto().getNombre(),
                detalleActual.getPrecioUnitario(),
                total
            };
            this.modelo.addRow(fila);
        }

        float descuento = 0;
        if (chkAplicarDescuento.isSelected() && this.personaEncontrada instanceof Cliente) {
            Cliente cliente = (Cliente) this.personaEncontrada;
            descuento = subTotal * (cliente.getFidelidad().getPuntosAcumulados() / 100.0f);
        }

        float iva = (subTotal - descuento) * 0.15f;
        float total = (subTotal - descuento) + iva;

        this.lblSubtotalPrice.setText(String.format("%.2f", subTotal));
        this.lblIvaPrice.setText(String.format("%.2f", iva));
        this.lblTotalPrice.setText(String.format("%.2f", total));

    }

    private void RegistrarFactura() {
        if (this.personaEncontrada != null && !this.detallesFactura.isEmpty()) {
            for (DetalleFactura detalle : this.detallesFactura) {
                if (detalle.getCantidad() > detalle.getProducto().getStock()) {
                    JOptionPane.showMessageDialog(this,
                            "Stock insuficiente para: " + detalle.getProducto().getNombre(),
                            "Error",
                            JOptionPane.ERROR_MESSAGE
                    );
                    return;
                }
            }

            Factura nuevaFactura = new Factura(this.personaEncontrada, this.detallesFactura);
            if (this.servicio.RegistrarFactura(nuevaFactura) == 0) { // Éxito
                if (this.personaEncontrada instanceof Cliente) {
                    Cliente cliente = (Cliente) this.personaEncontrada;
                    negocio.clienteServicio clienteServicio = new clienteServicio();
                    clienteServicio.acumularPuntos(cliente.getNumIdentificacion(), 1);
                }
            }
            JOptionPane.showMessageDialog(this, "Factura registrada.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeleteProductBill;
    private javax.swing.JButton btnGenerateInvoice;
    private javax.swing.JButton btnSearchProduct;
    private javax.swing.JCheckBox chkAplicarDescuento;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAmountProduct;
    private javax.swing.JLabel lblCodeProduct;
    private javax.swing.JLabel lblEmailUser;
    private javax.swing.JLabel lblHeaderName1;
    private javax.swing.JLabel lblHeaderName3;
    private javax.swing.JLabel lblInfoProduct;
    private javax.swing.JLabel lblIva;
    private javax.swing.JLabel lblIva1;
    private javax.swing.JLabel lblIvaPrice;
    private javax.swing.JLabel lblLastnameUser;
    private javax.swing.JLabel lblNameProduct;
    private javax.swing.JLabel lblNameUser;
    private javax.swing.JLabel lblNumIdUser;
    private javax.swing.JLabel lblPriceProduct;
    private javax.swing.JLabel lblSubtotal;
    private javax.swing.JLabel lblSubtotalPrice;
    private javax.swing.JLabel lblSystem;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblTotalPrice;
    private javax.swing.JTable tblListDetails;
    private javax.swing.JTextField txtAmountProduct;
    private javax.swing.JTextField txtCodeProduct;
    private javax.swing.JTextField txtEmailUser;
    private javax.swing.JTextField txtLastnameUser;
    private javax.swing.JTextField txtNameProduct;
    private javax.swing.JTextField txtNameUser;
    private javax.swing.JTextField txtNumIdUser;
    private javax.swing.JTextField txtNumIdenUser;
    private javax.swing.JTextField txtPriceProduct;
    // End of variables declaration//GEN-END:variables
}
