/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import javax.swing.table.DefaultTableModel;
import negocio.ProductoServicio;
import modelo.Producto;

/**
 *
 * @author sebas
 */
public class productoFrame extends javax.swing.JFrame {

    /**
     * Creates new form productoFrame
     */
    private ProductoServicio servicio;
    private final Border bordeRojo = BorderFactory.createLineBorder(Color.RED, 2);
    private final Border bordeNegro = BorderFactory.createLineBorder(Color.BLACK, 1);

    public productoFrame() {
        initComponents();
        servicio = new ProductoServicio();
        cargarDatos();
    }

    public void cargarDatos() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID");
        model.addColumn("Nombre");
        model.addColumn("Precio");
        model.addColumn("Codigo");
        for (Producto p : servicio.ListarProductos()) {
            Object[] fila = {p.getId(), p.getNombre(), p.getPrecio(), p.getCodigo()};
            model.addRow(fila);
        }
        tblProducto.setModel(model);

    }

    private void llenarFormularioDesdeTabla() {
        int filaSeleccionada = tblProducto.getSelectedRow();
        if (filaSeleccionada >= 0) {

            String nombre = tblProducto.getValueAt(filaSeleccionada, 1).toString();
            String precio = tblProducto.getValueAt(filaSeleccionada, 2).toString();
            String codigo = tblProducto.getValueAt(filaSeleccionada, 3).toString();

            nomTxtField.setText(nombre);
            precioTxtField.setText(precio);
            codigoTxtField.setText(codigo);
        }
    }

    public void agregar() {
        // Si el formulario esta lleno
        if (ValidarFormulario()) {
            System.out.println("Intentando registrar");

            double precio = 0.0;
            precio = Double.parseDouble(precioTxtField.getText());
            Producto nuevoProducto = new Producto(nomTxtField.getText(), precio,
                    codigoTxtField.getText());

            servicio.agregarNuevoProducto(nuevoProducto);
            cargarDatos();

        } else {
            System.out.println("Falta llenar un input");
            // Mostrar alerta de que llene el formulario

        }

    }

    public void editar() {
        int fila = tblProducto.getSelectedRow();
        if (fila >= 0) {

            int id = (int) tblProducto.getValueAt(fila, 0);

            String nuevoNombre = nomTxtField.getText();
            double nuevoPrecio = Double.parseDouble(precioTxtField.getText());
            String nuevoCodigo = codigoTxtField.getText();

            Producto productoEditado = new Producto(nuevoNombre, nuevoPrecio, nuevoCodigo);
            productoEditado.setId(id);

            servicio.ActualizarProducto(productoEditado);

            cargarDatos();
        } else {
            System.out.println("Seleccione una fila para editar.");
        }
    }

    private void vaciarCampos() {

        nomTxtField.setText("");
        precioTxtField.setText("");
        codigoTxtField.setText("");
    }

    public void eliminar() {
        int fila = tblProducto.getSelectedRow();
        if (fila >= 0) {
            int id = (int) tblProducto.getValueAt(fila, 0);

            int confirm = JOptionPane.showConfirmDialog(this, "¿Seguro que desea eliminar este producto?",
                    "Confirmar eliminación", JOptionPane.YES_NO_OPTION);
            if (confirm == JOptionPane.YES_OPTION) {
                servicio.EliminarProductoPorId(id);
                cargarDatos();
                vaciarCampos();

            }
        } else {
            System.out.println("Seleccione una fila para eliminar.");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRegistrarProducto = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProducto = new javax.swing.JTable();
        precioLabel = new javax.swing.JLabel();
        nombreLabel = new javax.swing.JLabel();
        nomTxtField = new javax.swing.JTextField();
        codigoLabel = new javax.swing.JLabel();
        codigoTxtField = new javax.swing.JTextField();
        precioTxtField = new javax.swing.JTextField();
        btnActualizarProducto = new javax.swing.JButton();
        btnVaciarCampos = new javax.swing.JButton();
        btnEliminarProducto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnRegistrarProducto.setText("Guardar");
        btnRegistrarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarProductoActionPerformed(evt);
            }
        });

        tblProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProductoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblProducto);

        precioLabel.setText("Precio:");

        nombreLabel.setText("Nombre: ");

        nomTxtField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        nomTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomTxtFieldActionPerformed(evt);
            }
        });

        codigoLabel.setText("Codigo:");

        codigoTxtField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        codigoTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoTxtFieldActionPerformed(evt);
            }
        });

        precioTxtField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        precioTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                precioTxtFieldActionPerformed(evt);
            }
        });

        btnActualizarProducto.setText("Editar");
        btnActualizarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarProductoActionPerformed(evt);
            }
        });

        btnVaciarCampos.setText("⟳");
        btnVaciarCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVaciarCamposActionPerformed(evt);
            }
        });

        btnEliminarProducto.setText("Eliminar");
        btnEliminarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarProductoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(nombreLabel)
                            .addGap(142, 142, 142)
                            .addComponent(nomTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(codigoLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                                .addComponent(precioLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(codigoTxtField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                                .addComponent(precioTxtField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnEliminarProducto)
                        .addGap(18, 18, 18)
                        .addComponent(btnActualizarProducto)
                        .addGap(18, 18, 18)
                        .addComponent(btnRegistrarProducto)))
                .addGap(34, 34, 34)
                .addComponent(btnVaciarCampos, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreLabel)
                    .addComponent(nomTxtField))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(precioLabel)
                    .addComponent(precioTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codigoLabel)
                    .addComponent(codigoTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(109, 109, 109)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnActualizarProducto)
                    .addComponent(btnEliminarProducto)
                    .addComponent(btnRegistrarProducto)
                    .addComponent(btnVaciarCampos, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarProductoActionPerformed
        agregar();
    }//GEN-LAST:event_btnRegistrarProductoActionPerformed

    private void nomTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomTxtFieldActionPerformed

    }//GEN-LAST:event_nomTxtFieldActionPerformed

    private void codigoTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoTxtFieldActionPerformed

    }//GEN-LAST:event_codigoTxtFieldActionPerformed

    private void precioTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precioTxtFieldActionPerformed

    }//GEN-LAST:event_precioTxtFieldActionPerformed

    private void tblProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProductoMouseClicked

        llenarFormularioDesdeTabla();

    }//GEN-LAST:event_tblProductoMouseClicked

    private void btnActualizarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarProductoActionPerformed
        editar();
    }//GEN-LAST:event_btnActualizarProductoActionPerformed

    private void btnVaciarCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVaciarCamposActionPerformed
        vaciarCampos();
    }//GEN-LAST:event_btnVaciarCamposActionPerformed

    private void btnEliminarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarProductoActionPerformed
        eliminar();
    }//GEN-LAST:event_btnEliminarProductoActionPerformed

    private boolean ValidarFormulario() {
        // pintar los bordes utilizando operador ternario
        nomTxtField.setBorder(nomTxtField.getText().isEmpty() ? bordeRojo : bordeNegro);
        precioTxtField.setBorder(precioTxtField.getText().isEmpty() ? bordeRojo : bordeNegro);
        codigoTxtField.setBorder(codigoTxtField.getText().isEmpty() ? bordeRojo : bordeNegro);

        return !(nomTxtField.getText().isEmpty() || precioTxtField.getText().isEmpty()
                || codigoTxtField.getText().isEmpty());
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(productoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(productoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(productoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(productoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new productoFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarProducto;
    private javax.swing.JButton btnEliminarProducto;
    private javax.swing.JButton btnRegistrarProducto;
    private javax.swing.JButton btnVaciarCampos;
    private javax.swing.JLabel codigoLabel;
    private javax.swing.JTextField codigoTxtField;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nomTxtField;
    private javax.swing.JLabel nombreLabel;
    private javax.swing.JLabel precioLabel;
    private javax.swing.JTextField precioTxtField;
    private javax.swing.JTable tblProducto;
    // End of variables declaration//GEN-END:variables
}
